handle nodes without "context" method defined
this happens when processing document like

hello::
world
goodbye::
cruel world

the above blocks are represented as a Asciidoctor::List, in which
the items are Array, which does not offer the "context" method.

in this change

* move the loop into process_interal()
* use map! updating the elements in blocks

otherwise we would have

asciidoctor_cjk_breaks/lib/asciidoctor/cjk_breaks_treeprocessor.rb:17:in `block in remove_cjk_breaks': asciidoctor: FAILED: /Users/kefu/dev/random-rants/_posts/2020-09-05-my-blog.adoc: Failed to load
AsciiDoc document - undefined method `context' for #<Array:0x00007f8cf56a2168> (NoMethodError)

Signed-off-by: Kefu Chai <tchaikov@gmail.com>